// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package hyperliquid

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonF3a0e9bbDecodeGithubComSoniricoGoHyperliquid(in *jlexer.Lexer, out *OrderStatusResting) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "oid":
			out.Oid = int64(in.Int64())
		case "cloid":
			if in.IsNull() {
				in.Skip()
				out.ClientID = nil
			} else {
				if out.ClientID == nil {
					out.ClientID = new(string)
				}
				*out.ClientID = string(in.String())
			}
		case "status":
			out.Status = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF3a0e9bbEncodeGithubComSoniricoGoHyperliquid(out *jwriter.Writer, in OrderStatusResting) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"oid\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Oid))
	}
	{
		const prefix string = ",\"cloid\":"
		out.RawString(prefix)
		if in.ClientID == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.ClientID))
		}
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OrderStatusResting) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF3a0e9bbEncodeGithubComSoniricoGoHyperliquid(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OrderStatusResting) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF3a0e9bbEncodeGithubComSoniricoGoHyperliquid(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OrderStatusResting) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF3a0e9bbDecodeGithubComSoniricoGoHyperliquid(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OrderStatusResting) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF3a0e9bbDecodeGithubComSoniricoGoHyperliquid(l, v)
}
func easyjsonF3a0e9bbDecodeGithubComSoniricoGoHyperliquid1(in *jlexer.Lexer, out *OrderStatusFilled) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "totalSz":
			out.TotalSz = string(in.String())
		case "avgPx":
			out.AvgPx = string(in.String())
		case "oid":
			out.Oid = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF3a0e9bbEncodeGithubComSoniricoGoHyperliquid1(out *jwriter.Writer, in OrderStatusFilled) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"totalSz\":"
		out.RawString(prefix[1:])
		out.String(string(in.TotalSz))
	}
	{
		const prefix string = ",\"avgPx\":"
		out.RawString(prefix)
		out.String(string(in.AvgPx))
	}
	{
		const prefix string = ",\"oid\":"
		out.RawString(prefix)
		out.Int(int(in.Oid))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OrderStatusFilled) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF3a0e9bbEncodeGithubComSoniricoGoHyperliquid1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OrderStatusFilled) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF3a0e9bbEncodeGithubComSoniricoGoHyperliquid1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OrderStatusFilled) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF3a0e9bbDecodeGithubComSoniricoGoHyperliquid1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OrderStatusFilled) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF3a0e9bbDecodeGithubComSoniricoGoHyperliquid1(l, v)
}
func easyjsonF3a0e9bbDecodeGithubComSoniricoGoHyperliquid2(in *jlexer.Lexer, out *OrderStatus) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "resting":
			if in.IsNull() {
				in.Skip()
				out.Resting = nil
			} else {
				if out.Resting == nil {
					out.Resting = new(OrderStatusResting)
				}
				(*out.Resting).UnmarshalEasyJSON(in)
			}
		case "filled":
			if in.IsNull() {
				in.Skip()
				out.Filled = nil
			} else {
				if out.Filled == nil {
					out.Filled = new(OrderStatusFilled)
				}
				(*out.Filled).UnmarshalEasyJSON(in)
			}
		case "error":
			if in.IsNull() {
				in.Skip()
				out.Error = nil
			} else {
				if out.Error == nil {
					out.Error = new(string)
				}
				*out.Error = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF3a0e9bbEncodeGithubComSoniricoGoHyperliquid2(out *jwriter.Writer, in OrderStatus) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Resting != nil {
		const prefix string = ",\"resting\":"
		first = false
		out.RawString(prefix[1:])
		(*in.Resting).MarshalEasyJSON(out)
	}
	if in.Filled != nil {
		const prefix string = ",\"filled\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.Filled).MarshalEasyJSON(out)
	}
	if in.Error != nil {
		const prefix string = ",\"error\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Error))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OrderStatus) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF3a0e9bbEncodeGithubComSoniricoGoHyperliquid2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OrderStatus) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF3a0e9bbEncodeGithubComSoniricoGoHyperliquid2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OrderStatus) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF3a0e9bbDecodeGithubComSoniricoGoHyperliquid2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OrderStatus) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF3a0e9bbDecodeGithubComSoniricoGoHyperliquid2(l, v)
}
func easyjsonF3a0e9bbDecodeGithubComSoniricoGoHyperliquid3(in *jlexer.Lexer, out *OrderResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "statuses":
			if in.IsNull() {
				in.Skip()
				out.Statuses = nil
			} else {
				in.Delim('[')
				if out.Statuses == nil {
					if !in.IsDelim(']') {
						out.Statuses = make([]OrderStatus, 0, 2)
					} else {
						out.Statuses = []OrderStatus{}
					}
				} else {
					out.Statuses = (out.Statuses)[:0]
				}
				for !in.IsDelim(']') {
					var v1 OrderStatus
					(v1).UnmarshalEasyJSON(in)
					out.Statuses = append(out.Statuses, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF3a0e9bbEncodeGithubComSoniricoGoHyperliquid3(out *jwriter.Writer, in OrderResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"statuses\":"
		out.RawString(prefix[1:])
		if in.Statuses == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Statuses {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OrderResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF3a0e9bbEncodeGithubComSoniricoGoHyperliquid3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OrderResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF3a0e9bbEncodeGithubComSoniricoGoHyperliquid3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OrderResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF3a0e9bbDecodeGithubComSoniricoGoHyperliquid3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OrderResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF3a0e9bbDecodeGithubComSoniricoGoHyperliquid3(l, v)
}
func easyjsonF3a0e9bbDecodeGithubComSoniricoGoHyperliquid4(in *jlexer.Lexer, out *ModifyOrderRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Oid":
			if m, ok := out.Oid.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Oid.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Oid = in.Interface()
			}
		case "Order":
			(out.Order).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF3a0e9bbEncodeGithubComSoniricoGoHyperliquid4(out *jwriter.Writer, in ModifyOrderRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Oid\":"
		out.RawString(prefix[1:])
		if m, ok := in.Oid.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Oid.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Oid))
		}
	}
	{
		const prefix string = ",\"Order\":"
		out.RawString(prefix)
		(in.Order).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ModifyOrderRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF3a0e9bbEncodeGithubComSoniricoGoHyperliquid4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ModifyOrderRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF3a0e9bbEncodeGithubComSoniricoGoHyperliquid4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ModifyOrderRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF3a0e9bbDecodeGithubComSoniricoGoHyperliquid4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ModifyOrderRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF3a0e9bbDecodeGithubComSoniricoGoHyperliquid4(l, v)
}
func easyjsonF3a0e9bbDecodeGithubComSoniricoGoHyperliquid5(in *jlexer.Lexer, out *CreateOrderRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Coin":
			out.Coin = string(in.String())
		case "IsBuy":
			out.IsBuy = bool(in.Bool())
		case "Price":
			out.Price = float64(in.Float64())
		case "Size":
			out.Size = float64(in.Float64())
		case "ReduceOnly":
			out.ReduceOnly = bool(in.Bool())
		case "OrderType":
			(out.OrderType).UnmarshalEasyJSON(in)
		case "ClientOrderID":
			if in.IsNull() {
				in.Skip()
				out.ClientOrderID = nil
			} else {
				if out.ClientOrderID == nil {
					out.ClientOrderID = new(string)
				}
				*out.ClientOrderID = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF3a0e9bbEncodeGithubComSoniricoGoHyperliquid5(out *jwriter.Writer, in CreateOrderRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Coin\":"
		out.RawString(prefix[1:])
		out.String(string(in.Coin))
	}
	{
		const prefix string = ",\"IsBuy\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsBuy))
	}
	{
		const prefix string = ",\"Price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	{
		const prefix string = ",\"Size\":"
		out.RawString(prefix)
		out.Float64(float64(in.Size))
	}
	{
		const prefix string = ",\"ReduceOnly\":"
		out.RawString(prefix)
		out.Bool(bool(in.ReduceOnly))
	}
	{
		const prefix string = ",\"OrderType\":"
		out.RawString(prefix)
		(in.OrderType).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"ClientOrderID\":"
		out.RawString(prefix)
		if in.ClientOrderID == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.ClientOrderID))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateOrderRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF3a0e9bbEncodeGithubComSoniricoGoHyperliquid5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateOrderRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF3a0e9bbEncodeGithubComSoniricoGoHyperliquid5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateOrderRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF3a0e9bbDecodeGithubComSoniricoGoHyperliquid5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateOrderRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF3a0e9bbDecodeGithubComSoniricoGoHyperliquid5(l, v)
}
