// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package hyperliquid

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC5a22aa7DecodeGithubComSoniricoGoHyperliquid(in *jlexer.Lexer, out *L2BookSubscriptionParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Coin":
			out.Coin = string(in.String())
		case "NSigFigs":
			out.NSigFigs = int(in.Int())
		case "Mantissa":
			out.Mantissa = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5a22aa7EncodeGithubComSoniricoGoHyperliquid(out *jwriter.Writer, in L2BookSubscriptionParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Coin\":"
		out.RawString(prefix[1:])
		out.String(string(in.Coin))
	}
	{
		const prefix string = ",\"NSigFigs\":"
		out.RawString(prefix)
		out.Int(int(in.NSigFigs))
	}
	{
		const prefix string = ",\"Mantissa\":"
		out.RawString(prefix)
		out.Int(int(in.Mantissa))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v L2BookSubscriptionParams) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5a22aa7EncodeGithubComSoniricoGoHyperliquid(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v L2BookSubscriptionParams) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5a22aa7EncodeGithubComSoniricoGoHyperliquid(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *L2BookSubscriptionParams) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5a22aa7DecodeGithubComSoniricoGoHyperliquid(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *L2BookSubscriptionParams) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5a22aa7DecodeGithubComSoniricoGoHyperliquid(l, v)
}
