// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package hyperliquid

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonA0f84c38DecodeGithubComSoniricoGoHyperliquid(in *jlexer.Lexer, out *AllMidsSubscriptionParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Dex":
			if in.IsNull() {
				in.Skip()
				out.Dex = nil
			} else {
				if out.Dex == nil {
					out.Dex = new(string)
				}
				*out.Dex = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA0f84c38EncodeGithubComSoniricoGoHyperliquid(out *jwriter.Writer, in AllMidsSubscriptionParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Dex\":"
		out.RawString(prefix[1:])
		if in.Dex == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Dex))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AllMidsSubscriptionParams) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA0f84c38EncodeGithubComSoniricoGoHyperliquid(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AllMidsSubscriptionParams) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA0f84c38EncodeGithubComSoniricoGoHyperliquid(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AllMidsSubscriptionParams) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA0f84c38DecodeGithubComSoniricoGoHyperliquid(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AllMidsSubscriptionParams) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA0f84c38DecodeGithubComSoniricoGoHyperliquid(l, v)
}
