// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package hyperliquid

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson7d2279f9DecodeGithubComSoniricoGoHyperliquid(in *jlexer.Lexer, out *CandlesSubscriptionParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Coin":
			out.Coin = string(in.String())
		case "Interval":
			out.Interval = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7d2279f9EncodeGithubComSoniricoGoHyperliquid(out *jwriter.Writer, in CandlesSubscriptionParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Coin\":"
		out.RawString(prefix[1:])
		out.String(string(in.Coin))
	}
	{
		const prefix string = ",\"Interval\":"
		out.RawString(prefix)
		out.String(string(in.Interval))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CandlesSubscriptionParams) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7d2279f9EncodeGithubComSoniricoGoHyperliquid(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CandlesSubscriptionParams) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7d2279f9EncodeGithubComSoniricoGoHyperliquid(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CandlesSubscriptionParams) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7d2279f9DecodeGithubComSoniricoGoHyperliquid(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CandlesSubscriptionParams) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7d2279f9DecodeGithubComSoniricoGoHyperliquid(l, v)
}
