// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package hyperliquid

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson1572b4ffDecodeGithubComSoniricoGoHyperliquid(in *jlexer.Lexer, out *TradesSubscriptionParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Coin":
			out.Coin = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1572b4ffEncodeGithubComSoniricoGoHyperliquid(out *jwriter.Writer, in TradesSubscriptionParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Coin\":"
		out.RawString(prefix[1:])
		out.String(string(in.Coin))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TradesSubscriptionParams) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1572b4ffEncodeGithubComSoniricoGoHyperliquid(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TradesSubscriptionParams) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1572b4ffEncodeGithubComSoniricoGoHyperliquid(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TradesSubscriptionParams) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1572b4ffDecodeGithubComSoniricoGoHyperliquid(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TradesSubscriptionParams) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1572b4ffDecodeGithubComSoniricoGoHyperliquid(l, v)
}
